### ISSUE TITLE
API Mismatch

### ISSUE THREAD

**Issue by BelleButCode** [ClaraCrazy/Flipper-Xtreme#102]
### Describe the bug.

I could just be stupid but for certain applications it says API version mismatch. Please help :sob:

### Reproduction

open apps with question mark icon (for example: dice_app)

**Comment by jbohack** [comment]
hello! in order to fix this issue, remove your 'apps' folder in qFlipper and reflash the firmware :)

**Comment by BelleButCode** [comment]
app data aswell or no?

**Comment by jbohack** [comment]
you should only need to clear 'apps'

**Comment by BelleButCode** [comment]
thank you :3

**Comment by jbohack** [comment]
no problem!
