### ISSUE TITLE
Read EMV-Card 

### ISSUE THREAD

**Issue by fe8769a** [ClaraCrazy/Flipper-Xtreme#107]
### Describe the bug.

Read EMV-Card  : display "reading card don't move " and nothing happens 

Can be read with standard reader as NFC-B immediatly

### Reproduction

just puut card under flipper

**Comment by ClaraCrazy** [comment]
team is unable to replicate, feel free to re-open with further details

**Comment by fe8769a** [comment]
Update to latest firmware . Process is NFC, extra action,read specific card ,read EMV card .-->reading card don't move , nothing happens for more than 10 minutes

**Comment by fe8769a** [comment]
Ok found some cards can be read some other no . Thanks for help
