### ISSUE TITLE
Tanks game Bricks Flipper

### ISSUE THREAD

**Issue by ItsHarryMo** [ClaraCrazy/Flipper-Xtreme#108]
### Describe the bug.

Open Tanks game coop (s) and flipper bricks. Forced to hold Return and Down button for 20+ seconds to get flipper to reboot with error "Flipper Crashed but has been rebooted - NULL Pointer dereference"

### Reproduction

Applications
Games
Tanks
Coop S
CRASH

### Target

TANKS GAME

**Comment by ClaraCrazy** [comment]
Sorry for the super-late response. This is a known issue of the game and nothing we can fix. feel free to tell the author of the game tho.

Thanks for using XFW!
