### ISSUE TITLE
Set Pin + Off

### ISSUE THREAD

**Issue by realSater** [ClaraCrazy/Flipper-Xtreme#118]
### Describe the bug.

Flipper Zero instantly turns off prior to setting up a PIN.

### Reproduction

1- Press `UP`
2- Select `Set PIN + Off` (make sure you don't have a pin setup previously)
3- a pin setup screen will show and then the FZ will instantly turn off

### Anything else?

This is a purely fresh setup environment.

**Comment by Willy-JL** [comment]
Good find, can reproduce it. Will take a look at it

**Comment by ZhengLinLei** [comment]
What does the `Set PIN + Off` really do?

**Comment by Willy-JL** [comment]
It makes you set a pin code, and then shuts off flipper...?

**Comment by jbohack** [comment]
this is now fixed :) new release will contain the fix
