### ISSUE TITLE
subghz playlist

### ISSUE THREAD

**Issue by johnjohnsp1** [ClaraCrazy/Flipper-Xtreme#126]
### Describe the bug.

Hi,
Updated the latest FW available (XFW 040), when you go browse the SD and create a file .txt under subplaylist/CAME/433 in order to craete a new playlist , the file itself appear correctly inside the folder but then when you try tu use it from application it doesn't show up

https://user-images.githubusercontent.com/1888855/217349809-ab087d9d-59a2-44ca-9317-e422ed51a498.mp4

inside the new file created the path for the files is like this:

sub: /ext/subghz/Garages/CAME-12bit-433/8/000_000.sub

i do something wrong ? anyone else get the same issue ?
thanks

### Reproduction

create new file on the SD under /subplaylist/*.txt , it will not show up when you start the application SubGhz Playlist from main menu

**Comment by Willy-JL** [comment]
Unleashed uses /ext/subplaylist, we use /ext/subghz/playlist. Files from previous firmwares remain, but might not be considered.
