### ISSUE TITLE
Unlocking picture not showing 

### ISSUE THREAD

**Issue by ZhengLinLei** [ClaraCrazy/Flipper-Xtreme#127]
### Describe the bug.

When I lock my flipper and I try to unlock it, the standard picture to press `back` `back` `back` is not showing.

However it shows a warning sign.

![IMG_20230211_092200](https://user-images.githubusercontent.com/77938581/218248225-572f4b95-f2ff-4e85-bc1a-426e283583c4.jpg)

### Reproduction

1. `Up`
2. Lock
3. It will show how to unlock

### Target

Unlock picture

**Comment by jbohack** [comment]
hello! so this isn't actually a bug. we replaced the dolphin warning asset in our firmware. thank you for reaching out with the concern though! :D
