### ISSUE TITLE
Support for external radio modules like the CC1101

### ISSUE THREAD

**Issue by hairyfred** [ClaraCrazy/Flipper-Xtreme#129]
### Description of the feature you're suggesting.

Similar to how Unleashed does it, a way to change which module the flipper uses for sub ghz.
https://github.com/quen0n/flipperzero-ext-cc1101

### Anything else?

Further down the line being able to use both the internal and an external one at the same time would be useful, but with the flippers limitations I'm not sure how easy/inuitive way to do this.

**Comment by ClaraCrazy** [comment]
Already in dev, patience is a virtue. checking the discord server is helpful too
