### ISSUE TITLE
Nice One (not really nice)

### ISSUE THREAD

**Issue by TheXHalferX** [ClaraCrazy/Flipper-Xtreme#131]
### Describe the bug.

So, trying emulating any key which uses Nice One 72bit protocol crashes Flipper. I can provide two files (basically two buttons of one gate remote) if necessary. I'm not sure if this is bug appeared here in XFW or has origin in Official Firmware. 

### Reproduction

1. Open file which uses Nice One 72 bit protocol
2. Press "Emulate"
3. Face the crash

### Target

Sub-Ghz

**Comment by ClaraCrazy** [comment]
Fixed in new release

**Comment by TheXHalferX** [comment]
Nice)
