### ISSUE TITLE
RFID Fuzzer

### ISSUE THREAD

**Issue by lanmic15** [ClaraCrazy/Flipper-Xtreme#133]
### Describe the bug.

Hey Clara,
I was playing around with some RFID Reader.
I try multiple times the RFID Fuzzer App but it won't run correctly.
It crashes the Firmware and pass out the flipper without letting me safe anything.

### Reproduction

After starting RFID-Fuzzer with "Load File" or "Load UIDs from File" the Flipper chrashed with the Info "BusFault"

**Comment by ClaraCrazy** [comment]
Fixed in new release
