### ISSUE TITLE
467.989 ghz always on

### ISSUE THREAD

**Issue by maximed911** [ClaraCrazy/Flipper-Xtreme#136]
### Describe the bug.

467.989 and 468.009 ghz always on when using frequency analyzer in house... it was never detected before update V41_02142023.

unlshd V.30 have made this update:

SubGHz: Remove 467.75 From freq analyzer since it has too much noise (Frequency is still can be used, just excluded from FA to avoid false detections

### Reproduction

just go in frequency analyzer lol

### Target

Frequency analyzer

**Comment by jbohack** [comment]
hello, this is actually intended since the frequency analyzer is meant to inform you of all common frequencies that are seen. it isn't noise-related it's just a very common pager frequency that you can read with the 'Pagers' modulation :)

**Comment by maximed911** [comment]
Alright thanks. Sorry for the inconvenience :)

Le mer. 15 févr. 2023, 6 h 11 p.m., jbohack ***@***.***> a
écrit :

**Comment by Willy-JL** [comment]
Small correction: yeah it is background noise, i heard its from the internal chip itself, but not sure. Anyway I would rather keep it and just have users use a higher RSSI threshold instead of removing it completely personally

**Comment by maximed911** [comment]
iight np :)
Le mer. 15 févr. 2023, 7 h 44 p.m., WillyJL ***@***.***> a
écrit :
