### ISSUE TITLE
Ext IR module

### ISSUE THREAD

**Issue by macgyverfuerarme** [ClaraCrazy/Flipper-Xtreme#141]
### Describe the enhancement you're suggesting.

Would be cool to implement a possibility to use a external ir module Like this to increase the range of IR. Like the new feature in the subghz. Maybe a mosfet module+battery is needed.
https://a.aliexpress.com/_mszL3nu

**Comment by ClaraCrazy** [comment]
There is an external IR feature included, been there for ages. Works by default.
