### ISSUE TITLE
airtag detector

### ISSUE THREAD

**Issue by smannchen** [ClaraCrazy/Flipper-Xtreme#151]
### Describe the enhancement you're suggesting.

I was curious if something similar to this could be implemented?
https://www.kickstarter.com/projects/1458746827/bluesleuth-lite-detect-hidden-airtags
I know (Due to RM's slip up) that it can definitely emulate one. So I thought this would be a much better idea.
It would be a great tool not only for personal safety, but for TCSM as well.

**Comment by ClaraCrazy** [comment]
why tf is that device 499$ lmao. I could probably build it for 20


also, after actually reading this here. We wont be able to do that. The Flipper doesnt have a full BT stack required to do such tasks

**Comment by cgibsonmm** [comment]
Any ideas of boards that could support this?
