### ISSUE TITLE
Standalone MFKey32 app (.fap)

### ISSUE THREAD

**Issue by WatskeBart** [ClaraCrazy/Flipper-Xtreme#157]
### Describe the enhancement you're suggesting.

Could you add [FlipperMfkey](https://github.com/noproto/FlipperMfkey) to XFW?
Current API version is not compatible with XFW.

This app (.fap) makes Mifare cracking possible without using the Flipper companion app on your phone.

### Anything else?

Keep up the clean coding, and hope v42 will be available soon ;)

**Comment by skynet01** [comment]
Meanwhile you can the latest fap file here: https://github.com/xMasterX/unleashed-extra-pack/tree/main

**Comment by ClaraCrazy** [comment]
a fap literally doesnt help at all, since it cant be used on different fw

**Comment by skynet01** [comment]
I thought fap is API dependent? So as long as both Unleashed and your firmware is on the same version wouldn't they work?  I used a few faps from that link including the one that's requested and they all worked for me.

**Comment by ClaraCrazy** [comment]
Updated previous comment, not sure what I was on about. 

FAPs work as long as our API version is the same, yes.

**Comment by Willy-JL** [comment]
Added, will be in v43

**Comment by LevitatingBusinessMan** [comment]
Does this app add anything seeing as MFKey32 seems to be built into the firmware?
