### ISSUE TITLE
Bluetooth remote enhancements - based on previous issue raised

### ISSUE THREAD

**Issue by TheMany172** [ClaraCrazy/Flipper-Xtreme#159]
### Describe the enhancement you're suggesting.

Can confirm that I am now able to connect flipper with bluetooth remote - however prior to connecting it just showed a macaddress in the scan - not the usual 'control [name of flipper]'

#### If possible would also be good to add one or more of these

- [ ] return to showing 'control [name of flipper]' - or even choose the name like in BK

- [ ] able to see device label that the Bluetooth remote is connected to

- [ ] be able to disconnect from is using the flipper

- [ ] be able to browse and choose what to connect to from the flipper

**Comment by ClaraCrazy** [comment]
- done
- not possible
- turn off bt
- not possible

**Comment by Willy-JL** [comment]
For more info on the not possible's: flipper uses the BLE light stack, which only allows acting as a 'slave' and not a 'master' devices (yes the technical terms could be better). This means that devices connect TO flipper, while flipper cannot see or connect to other devices

**Comment by TheMany172** [comment]
Thanks both for the elaboration, explaination and speed - I will bear it in mind

I have tried connecting to my android phone and the scan shows a mac address - I have tried connecting to a macbook and it shows 'generic device'

once either are actually connected it then shows 'Control [nameofflipper]'

not the end of the world tho
