### ISSUE TITLE
Bad KB doesn't work

### ISSUE THREAD

**Issue by slimshotty** [ClaraCrazy/Flipper-Xtreme#163]
### Describe the bug.

Bad KB doesn't work. After trying to access, no other options work except for Settings. Soft reboot corrects the issue until you try to access Bad KB again.

### Reproduction

1. Switch on
2. Access Bad KB.
3. Access anything else but Settings as Settings will work.
4. To recover, soft reboot device.

**Comment by Willy-JL** [comment]
Cant reproduce... mind sending a video of it happening, or joining our discord and making a ticket for this?

**Comment by slimshotty** [comment]
Now it is working for me, however, after repeating the steps, I received the Oh shit screen stating there was some type of overflow.  I should have captured the screen since I hit it twice.  As I continued to try to access Bad KB, it finally worked.

I'm wondering if it's because of the amount of scripts/nested folders I have under Bad KB.

I promise next time to capture a video or at the very least a screenshot.

**Comment by slimshotty** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/20408676/224170511-6ccbd4ab-dfc4-4644-85cb-a4b1a4e86994.png">

**Comment by Willy-JL** [comment]
So this is a duplicate of #162 then. Good to know it’s not 2 separate issues
