### ISSUE TITLE
Barcode app save display 

### ISSUE THREAD

**Issue by salutcalin2002** [ClaraCrazy/Flipper-Xtreme#165]
### Description of the feature you're suggesting.

I have the barcode fap app from another fw and works amazing to generate and save barcodes as well and display them . It's not included yet would be fun to have it for all users . Directly from the firmware.

**Comment by Willy-JL** [comment]
it is included, look in misc

**Comment by salutcalin2002** [comment]
It's not the same one this let's you as well to save and edit your own and do a list there two of them .

**Comment by salutcalin2002** [comment]
It's called barcode.fap not barcode generator .there different

**Comment by Willy-JL** [comment]
mind providing a link then? this is really generic...

**Comment by salutcalin2002** [comment]
Yes if I could uploaded somewhere immediately retuning with it on weshare

**Comment by salutcalin2002** [comment]
[https://wetransfer.com/downloads/e36ead9bba3bf01fa9ca71d4b804e59b20230310105836/e595b4e485274378f16df2e1494fcfb420230310105847/3f819c](https://wetransfer.com/downloads/e36ead9bba3bf01fa9ca71d4b804e59b20230310105836/e595b4e485274378f16df2e1494fcfb420230310105847/3f819c?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)


there are the two one in the fw and the one missing :) 

thank you so much !!! best fw ever ! i told everyone on reddit and git :) how professional it is

**Comment by salutcalin2002** [comment]
https://we.tl/t-NDX9J1i2ui?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05

**Comment by ClaraCrazy** [comment]
not helping at all

**Comment by ClaraCrazy** [comment]
either send us the source or we cant include it

**Comment by salutcalin2002** [comment]
this is the the source
https://github.com/Kingal1337/flipper-barcode-generator

**Comment by Willy-JL** [comment]
Done, will be in v43
