### ISSUE TITLE
Option to configure left arrow key

### ISSUE THREAD

**Issue by skynet01** [ClaraCrazy/Flipper-Xtreme#167]
### Describe the enhancement you're suggesting.

Would be awesome if we could set the favorite app for the left arrow key press just like we can for up and down arrows :) 

Thank you so much this awesome firmware :) 

### Anything else?

Keep on being amazing, this firmware fucks

**Comment by ClaraCrazy** [comment]
left arrow keys are already set for other thing. two favorites are enough, others only give one, and it would just take away functionality
