### ISSUE TITLE
Keyboard last row's keys are offset by 1

### ISSUE THREAD

**Issue by BrunoKlu** [ClaraCrazy/Flipper-Xtreme#168]
### Describe the bug.

When navigating between numbers of the on screen numeric keyboard on the right of the letters keyboard : 

If 8 is selected , then pressing up arrow, 6 is selected instead of 5 and vice versa

if 7 is selected, then pressing up arrow, 5 is selected instead of 4 and vice versa 

if 9 is selected, then pressing up arrow, selection disappears.

if “save” is selected, then pressing up arrow goes to 4 instead of “delete” and vice versa

Hope my explanations are more or less clear…

Thanks 🙏 

### Reproduction

1. Go anywhere in Flipper where you use the on screen keyboard
2. On the keyboard navigate to the numeric keyboard with arrows 
3. Put selection on “save” “7”,”8” or “9”
4. Press up arrow

**Comment by Willy-JL** [comment]
Right, added to todo list

**Comment by Willy-JL** [comment]
Fixed via 2b68bf7542d8d54b5cb2f3e75e0a8062cf75f2a7
