### ISSUE TITLE
Subghz read function setting memory

### ISSUE THREAD

**Issue by Przemekmac1** [ClaraCrazy/Flipper-Xtreme#173]
### Describe the enhancement you're suggesting.

It would be great if SubGhz/Read could remember last settings from “config”. 
For example I would like to have “Bin RAW” option by default ON.

**Comment by We-sing-in-e** [comment]
yes

**Comment by Willy-JL** [comment]
The tradoff isn't really worth it, adds more complexity to it in terms of the implementation, and also the internal storage is limited
