### ISSUE TITLE
are you not updating this anymore?

### ISSUE THREAD

**Issue by merrychrishna** [ClaraCrazy/Flipper-Xtreme#174]
### Describe the enhancement you're suggesting.

this hasnt been updated since january, are you not going to be updating anything anymore?

**Comment by AWulf1** [comment]
This has been updated last week please check the latest releases here https://github.com/ClaraCrazy/Flipper-Xtreme/releases/tag/XFW-0042_09032023

**Comment by merrychrishna** [comment]
oh sweet. thanks
