### ISSUE TITLE
Sub-GHz Remote

### ISSUE THREAD

**Issue by TheXHalferX** [ClaraCrazy/Flipper-Xtreme#175]
### Describe the bug.

Opening app is no go due to error:
“Load failed. Found unsatisfied imports”

### Reproduction

1. Open “Sub-GHz Remote” app
2. Error

### Target

Sub-GHz app

**Comment by ClaraCrazy** [comment]
Sounds like you compiled the dev version, which isnt recommended and theres also no support for dev branch.

**Comment by TheXHalferX** [comment]
I see) Sorry, just wanted to give you a heads up)
