### ISSUE TITLE
SubGhz menu memory lost on saving

### ISSUE THREAD

**Issue by BrunoKlu** [ClaraCrazy/Flipper-Xtreme#176]
### Describe the bug.

SubGhz settings menu loosing configuration after going to the saving section

### Reproduction

1. Go in Subghz menu
2. Select Read
3. Left arrow for settings
4. Chose Hopping : On
5. Press back
6. Wait to receive a signal (use bin raw to get one faster)
7. Click on a signal
8. Righ arrow save
9. Save or not
10. Back to reading screen 
11. Left arrow for Settings 
12. Setting is back to Hopping : Off

### Anything else?

❤️🙏

**Comment by ClaraCrazy** [comment]
Not a bug. intended feature. saving those settings would take up more very valuable space and provide not enough functionality to warrant that. We only have like 30kb left that we can work with. Not really something we can consider as of right now
