### ISSUE TITLE
Sub-GHz NSFW Read Mode bug

### ISSUE THREAD

**Issue by Teresium** [ClaraCrazy/Flipper-Xtreme#179]
### Describe the bug.

With NFSW package in Read mode can't see if it's "Int" or "Ext" module.

### Reproduction

1. Xtreme setting Graphic to NSFW
2. Sub-GHz -> Read
3. Top screen "Int" or "Ext" not clearly visible

**Comment by ClaraCrazy** [comment]
Fixed in release
