### ISSUE TITLE
BadUSB BT re-pair

### ISSUE THREAD

**Issue by cr4ck32** [ClaraCrazy/Flipper-Xtreme#180]
### Describe the bug.

When I configure the name of the device in bluetooth and then attack for example in windows or android, it works fine, but if I exit the application and go back in to perform the attack again, I have to pair the device again, why? thank you so much.

### Reproduction

1. Open Bad KB (for example demo_windows)
2.      < Settings
3.      Select Connection: BT
4.      Change the name in BT: example_name_device
5.      Connect to your flipper
6.      Approve code
7.      ?????
8.      Attack: Done Ok
9.      closing demo_windows
10.      Opening demo_windows again
11. The victim computer does not recognize the device (re-pair again)

### Target

Bad KB

### Logs

```Text
none
```

### Anything else?

Could there be a solution for not pairing again if it had already been paired before? thank you!

Note: I have the latest version installed (firmware)

Thanks!

**Comment by Willy-JL** [comment]
There is an option called "remember", and yes it does exactly what it sounds like

**Comment by cr4ck32** [comment]
@Willy-JL I already tried, but it asks for pairing again when I exit the app bad KB, thanks
