### ISSUE TITLE
BadKB 

### ISSUE THREAD

**Issue by Bob337** [ClaraCrazy/Flipper-Xtreme#186]
### Describe the bug.

When I connect to pc by bluetooth  and BadKB app and try to run script I am getting error:
error no keybord defined for rem

### Reproduction

1. click on BADKB app
2. choose script 
3. click on run

**Comment by Willy-JL** [comment]
That error message does not exist, I assume you mean "No keycode defined for ...".

And that seems to be an issue with your script, the `REM` command works perfectly fine here. Note that `REM` needs to all capital, and at the beginning of the line. No spaces before it, and no lowercase letters.
