### ISSUE TITLE
Backlight and volume toggles

### ISSUE THREAD

**Issue by TheXHalferX** [ClaraCrazy/Flipper-Xtreme#187]
### Describe the enhancement you're suggesting.

I mean that sliders are helpful af, but sometimes it's more convenient to turn on or off volume/backlight right away. Other elements in menu act like buttons, so here's what: you can add this button press to sliders to toggle them, say for example 45% brightness to zero and vice versa. Same goes for volume control.

**Comment by Willy-JL** [comment]
This would require some changes to the notification service handler to remember the previous values, and the tradeoff for that is too slim to consider, sorry
