### ISSUE TITLE
Emulating RFID or sending RFID from mobile app broken again

### ISSUE THREAD

**Issue by Codeplaya** [ClaraCrazy/Flipper-Xtreme#189]
### Describe the bug.

On V42 this was working.

Currently Wewn you open mobile app, go to the archive tab, choose any saved items, marked as RFID 125 or  Sub-GHz then pressing Send for the Sub-GHz or Emulate for the RFID 125, does not activate anything on flipper.

NFC and iButton works, however

### Reproduction

Read and save any RFID 125 to Flipper.
Download and install Flipper mobile app.
Open app, pair your flipper to your phone via bluetooth.
Wait until app synchronizes your saved items to the archive.
Open archive tab in the mobile app(middle, folder icon on the bottom ribbon)
Tap your saved RFID125 on the mobile app
Tap Emulate
Nothing happens.
Read and save any NFC to Flipper.
Open archive tab in the mobile app(middle, folder icon on the bottom ribbon)
Tap your saved NFC on the mobile app
Tap Emulate
Flipper starts emulating.
Tap Emulate again
Flipper stops emulating.

**Comment by ClaraCrazy** [comment]
nothing changed on that code, the mobile app is known to not work with cfw

**Comment by Codeplaya** [comment]
While you can make that argument, I mostly agree. It has never worked with cfw. But it was working with V42. Broken with V41. So it must be related to some other part of the code.
