### ISSUE TITLE
Screen error graphics

### ISSUE THREAD

**Issue by park0urakos** [ClaraCrazy/Flipper-Xtreme#190]
### Describe the bug.

screen error start  with "ligma" flipper screen restart, almost every animation change follow with error, also flipper zero getting slower. 

### Reproduction

 restoring flipper zero with ofw have no issius, any other action not help.

**Comment by salutcalin2002** [comment]
Same issue some weird text over other text Ligma and then flipper crash reboot

**Comment by wfosborn** [comment]
Same issue here after locking keypad and leaving it overnight. Somewhere along trying to reboot and get it working threw a null pointer  dereference. Had to restore original firmware, haven't been able to put Xtreme back on it yet without the same thing happening though.

**Comment by achtnullzwei** [comment]
Same issue. Going to try wfosborn's suggestion on formatting the card to fix this.

**Comment by park0urakos** [comment]
I format sd card and restore flipper zero, I install previous version of Xtreme and im ok for the moment till next update.

**Comment by salutcalin2002** [comment]
![Uploading IMG_5569.jpeg…]()

**Comment by salutcalin2002** [comment]
![IMG_5566](https://user-images.githubusercontent.com/125278319/229312058-9972bbd2-56ab-48f3-aba3-4c73d14a7cec.jpeg)
![IMG_5568](https://user-images.githubusercontent.com/125278319/229312060-98b4cc31-7865-41f4-a20d-54b1094938eb.jpeg)
![IMG_5567](https://user-images.githubusercontent.com/125278319/229312061-93d12a90-4643-4313-a91b-1d274ff5e119.jpeg)

**Comment by maddawg836** [comment]
Same here. Keep getting ligma almost every other screen sometimes. I can go back to unleashed again and all animations work again.

**Comment by ClaraCrazy** [comment]
@maddawg836 @achtnullzwei @wfosborn @salutcalin2002 @park0urakos 

Welcome to the world of april fools

get some help you basement dwellers with no sense of reality

**Comment by achtnullzwei** [comment]
@ClaraCrazy good one.

**Comment by maddawg836** [comment]
You know I knew it was a screen animation since the real time clock was fine and I didn't get the issue yesterday which is the first time installing this cfw. That was a good one, ligma.... 

> @maddawg836 @achtnullzwei @wfosborn @salutcalin2002 @park0urakos
> 
> Welcome to the world of april fools
> 
> Yall are goofy
> 
> ![IMG_20230401_234134.jpg](https://user-images.githubusercontent.com/55334727/229315394-44bc8f07-e56c-4330-bbc6-33eeaa810684.jpg)

You know I knew it was a screen animation since the real time clock was fine and I didn't get the issue yesterday which is the first time installing this cfw. That was a good one and ironic timing, ligma....

**Comment by wfosborn** [comment]
@ClaraCrazy My family got a good laugh out of it later this morning when I finally pieced it together too. 😂 Even told myself this morning "Remember it's April Fool's and don't fall for anything this year." 🤦🏻‍♂️

**Comment by salutcalin2002** [comment]
Amazing team xtreme amazing firmware 🍻💪😃

**Comment by jahmaogak0** [comment]
L3_Sunflower_128x64 is the animation name btw
