### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by Cypher212** [ClaraCrazy/Flipper-Xtreme#191]
### Describe the bug.

After adding my own custom animations, I get spammed with the "huge thanks to my team" animation and I can't get rid of it even through the manifest.txt, my animations are there but the "thanks" animation keeps appearing so many times, thanks for your amazing work nonetheless Clara!

### Reproduction

switching animations keeps getting "Huge thanks to my team" many times

### Target

"huge thanks to my team"

**Comment by Willy-JL** [comment]
That's not a bug, that's something wrong with your animation. Possibly too many frames (I wouldn't recommend more than 40), or images are too big in size. Maybe you haven't updated your asset packer script?
