### ISSUE TITLE
My device Bluetooth name doesn't show up.

### ISSUE THREAD

**Issue by FirestormeDS** [ClaraCrazy/Flipper-Xtreme#194]
### Describe the bug.

Hello as the tittle suggest my device Bluetooth name doesn't show up on the application of flipper on android. I tried restarting it many times but nothing. But the thing is that it show up on my phone Bluetooth list and i can connect.

### Reproduction

Normal on/off Bluetooth

**Comment by ClaraCrazy** [comment]
Fixed in latest dev via 525376df9e4c909087c18091a92e7dfa39b55a20, and will be in the next release

**Comment by charlieporth1** [comment]
I have this issue as well. Just putting this here for a +1

**Comment by ClaraCrazy** [comment]
Fixed in latest release

**Comment by FirestormeDS** [comment]
Thanks for your hard work :) . Really thx
