### ISSUE TITLE
NFC Maker App (BT MACs, URLs, Phone Nums, Emails, WiFis, Text Notes)

### ISSUE THREAD

**Issue by BoomSec** [ClaraCrazy/Flipper-Xtreme#195]
### Describe the enhancement you're suggesting.

Allow users to generate nfc codes based on what information they want to share. For example, allow users to share files stored on the flipper making for easy transfers during flipper meetups. Or allow people to enter urls into the flipper and then share them via nfc. A possible use case would be an nfc business card / contact. Tapping a phone against the flipper would allow users to add the contact that is being stored in the nfc code.

**Comment by park0urakos** [comment]
I tried to pay with NFC that i copied my Bank account and emulated, but every pos system that i tried not recognise it. Any suggestions - bug - recommendation - issue - help?

**Comment by ClaraCrazy** [comment]
> I tried to pay with NFC that i copied my Bank account and emulated, but every pos system that i tried not recognise it. Any suggestions - bug - recommendation - issue - help?

Its not possible to pay with a flipper, lol

**Comment by ClaraCrazy** [comment]
> ### Describe the enhancement you're suggesting.
> Allow users to generate nfc codes based on what information they want to share. For example, allow users to share files stored on the flipper making for easy transfers during flipper meetups. Or allow people to enter urls into the flipper and then share them via nfc. A possible use case would be an nfc business card / contact. Tapping a phone against the flipper would allow users to add the contact that is being stored in the nfc code.
> 
> ### Anything else?
> _No response_

You can already do that on a phone and transfer it to the flipper. creating a whole app is tedious and the added value of this just isnt enough to justify it right now. 

-> Backlog'd

**Comment by park0urakos** [comment]
> > I tried to pay with NFC that i copied my Bank account and emulated, but every pos system that i tried not recognise it. Any suggestions - bug - recommendation - issue - help?
> 
> Its not possible to pay with a flipper, lol

Thnx for help.

**Comment by Willy-JL** [comment]
Now fully implemented, will be in next release. Not on github yet however, not gonna put it anywhere until we release so a certain someone can't steal it (I know you're reading this, hey RM! :wave: )

Preview:
![image](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/49810075/8fd6c067-11b0-47af-8093-ea9618c64369)

**Comment by BoomSec** [comment]
Thanks for bringing this back you legend 😎😎

**Comment by analyserdmz** [comment]
> Now fully implemented, will be in next release. Not on github yet however, not gonna put it anywhere until we release so a certain someone can't steal it (I know you're reading this, hey RM! 👋 )
> 
> Preview: ![image](https://user-images.githubusercontent.com/49810075/246693730-8fd6c067-11b0-47af-8093-ea9618c64369.png)

Any potential release date for this? 💯

**Comment by Willy-JL** [comment]
> Any potential release date for this?

![soon-tm-soon](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/49810075/4e19b6f1-ab1e-4933-bd77-f575ff0f9f65)

**Comment by BoomSec** [comment]
Fr asking how long a piece of string is

**Comment by r4p7us** [comment]
I did something like this..

[Termux_open_by_Raptus.zip](https://github.com/ClaraCrazy/Flipper-Xtreme/files/11905140/Termux_open_by_Raptus.zip)

**Comment by ClaraCrazy** [comment]
imagine thinking I'd let anyone upload a random fucking zip file... :-1:

**Comment by r4p7us** [comment]
no sorry, I just wanted to post an example nfc file to open an app with the pinball machine via nfc, that's all, since raw wouldn't let me send it, I zipped it.

**Comment by ClaraCrazy** [comment]
use gist, please. gist.github.com

**Comment by r4p7us** [comment]
okay sorry

**Comment by Willy-JL** [comment]
@RogueMaster bounty time? kek
