### ISSUE TITLE
Mobile App commands 

### ISSUE THREAD

**Issue by tengen-toppa-gurren-lagann** [ClaraCrazy/Flipper-Xtreme#196]
### Describe the bug.

Mobile app commands can't reach Flipper despite being properly connected and synced via Bluetooth.

### Reproduction

1. Connect to Flipper using official Flipper Android app.
2. Wait until synchronization is complete.
3. Choose "Archive"
4. Try to run anything from there.

**Comment by ClaraCrazy** [comment]
Flipper Mobile app barely works for any custom firmware, cant really change that. 

Closing as duplicate of GH-189
