### ISSUE TITLE
SubGhz - External radio module setting reverts to internal

### ISSUE THREAD

**Issue by fzarada** [ClaraCrazy/Flipper-Xtreme#206]
### Describe the bug.

I'm on [XFW-0044_09042023](https://github.com/ClaraCrazy/Flipper-Xtreme/releases/tag/XFW-0044_09042023) using an external CC11001 module with 5V supply. Setting SubGhz>Radio Settings>Module to external works, however upon exiting SubGhz menu to desktop, the radio setting reverts to internal. This makes some external SubGhz apps not having access to the external module.
I understand the Flipper would revert to internal radio on next bootup, but this is occurring on menu exit. 

Strangely enough, this issue does not occur while Flipper is connected to PC via USB.

### Reproduction

1. Attach an external CC11001 module
2. Navigate to SubGhz>Radio Settings>Module and set to external
3. Exit out of SubGhz back to main menu grid
4. Navigate back to >Radio Settings>Module
5. The module is back to internal

Now connect Flipper to PC and redo 2,3,4, the module stays as external until disconnected from PC while outside SubGhz menu.

**Comment by ClaraCrazy** [comment]
Not a bug, simply not storing the settings as it the flippers low storage doesnt really allow us. 4k block size means every settings file takes up at least 4kb, and internal storage only has like 28 or so left. not viable.
