### ISSUE TITLE
tanks co-processor bug

### ISSUE THREAD

**Issue by zerocoooooooooool** [ClaraCrazy/Flipper-Xtreme#208]
using current update tried playing tanks single player had a co-processor error and bricked the flipper....was able to recover but was completely unresponsive until using qflipper  probably a issue with tanks but wanted to help people avoid this issue

**Comment by ClaraCrazy** [comment]
Please report the issue to the creator of the app, we dont have the time to fix 50+ different apps. We only include them because otherwise everyone cries.

**Comment by zerocoooooooooool** [comment]
just thought you could warn people about its non compatibility and possibility of bricking their flipper
