### ISSUE TITLE
Unable to reset name to default

### ISSUE THREAD

**Issue by ggppjj** [ClaraCrazy/Flipper-Xtreme#213]
### Describe the bug.

The firmware says "leave empty for default", but does not allow you to save an empty value. Saving a space sets the name to " ".

### Reproduction

Change name of device in Xposed settings.

Attempt to reset it to the factory name.

**Comment by Willy-JL** [comment]
Fixed via 2d794b32f54509dee74b0ae443ec377b9cc69dc7 and 4f4895d08b32bf9ae0b899fec27caa348d5caaf6
