### ISSUE TITLE
Bluetooth not connecting discretely anymore

### ISSUE THREAD

**Issue by St31th** [ClaraCrazy/Flipper-Xtreme#217]
### Describe the bug.

Before the change to badbt, if my phone was connected to a bt speaker, I could name the flipper the same name and turn off the speaker and my phone would automatically connect to the flipper. Now it doesn’t and no matter what it always pops up a request to connect message on my phone now. 

### Reproduction

Just connect to badkb using Bluetooth on a phone

**Comment by Willy-JL** [comment]
did you try toggling the remember option, on both modes?

also, if it worked that way before, that is not an intended feature of badkb. that *should not* happen. if it did, that is some serious security vulnerability on your phone my friend

**Comment by ClaraCrazy** [comment]
@
