### ISSUE TITLE
 Subghz freezing issue

### ISSUE THREAD

**Issue by ghost** [ClaraCrazy/Flipper-Xtreme#219]
### Describe the bug.

While testing external cc1101 module or when I enter radio setting, flipper zero freezes and I have to restart, but there is no such problem in unleshead version please fix this problem.

### Reproduction

...

### Target

External subghz

**Comment by ClaraCrazy** [comment]
user deleted account, lol

**Comment by Hitmanreis** [comment]
Aynı sorunu yaşıyorum sorun ne zaman çözülecek?
