### ISSUE TITLE
External cc1101 error

### ISSUE THREAD

**Issue by Hitmanreis** [ClaraCrazy/Flipper-Xtreme#220]
### Describe the enhancement you're suggesting.

While testing external cc1101 module or when I enter radio setting, flipper zero freezes and I have to restart, but there is no such problem in unleshead version please fix this problem.
Another user's comment I'm having this same problem

**Comment by Hitmanreis** [comment]
The bugs have been fixed with the latest software version, I think when will it update?

**Comment by Willy-JL** [comment]
when its ready

**Comment by Hitmanreis** [comment]
Can you add something for sex toys? ☺️

**Comment by Willy-JL** [comment]
1. that has nothing to do with broken external cc1101
2. we make firmware not files and recordings

**Comment by Hitmanreis** [comment]
CC1101 cc1101 3. pin flipper zero 6. When I remove the b2 pin, my cc1101 device works more stable and the freezing problem is removed. What is the problem, is it any harm if I don't use this pin? It detects remote signals without any problems.


![IMG_20230428_142402](https://user-images.githubusercontent.com/131968292/235135402-6a9946bc-7611-4c70-a6a7-3f183ee5d4aa.jpg)
![IMG_20230428_142405](https://user-images.githubusercontent.com/131968292/235135411-6c3c6edc-833f-42cc-9d2e-73bd6d4597eb.jpg)
![IMG_20230428_142426](https://user-images.githubusercontent.com/131968292/235135415-462a3473-fc62-484c-880c-96f190502c8a.jpg)

**Comment by ClaraCrazy** [comment]
fixed in new update

**Comment by Hitmanreis** [comment]
Sorun devam ediyor https://youtube.com/shorts/nHUoJRY3u2Y?feature=share

**Comment by ClaraCrazy** [comment]
code ia the exact same as in unleashed

**Comment by Hitmanreis** [comment]
I installed rogue master and xtreme firmware, the problem is the same, what can I do?  i changed my device for the 2nd time i changed the cables too

**Comment by Hitmanreis** [comment]
it's not just spam, it crashes when I switch to the signaling menu without reading sample signal in different menus, it is fixed when I restart the problem

**Comment by Hitmanreis** [comment]
friends who have the same problem, I solved the problem by plugging the pins into 3v input instead of 5v, I am attaching a photo
![Screenshot_2023-05-03-21-46-49-490_com google android youtube](https://user-images.githubusercontent.com/131968292/236024836-e6a11d1b-48ae-4ad5-8c7e-122e99fb92a4.jpg)
