### ISSUE TITLE
修改菜单显示文字支持UTF-8

### ISSUE THREAD

**Issue by LuckyFishGeek** [ClaraCrazy/Flipper-Xtreme#222]
### Describe the bug.

I want to change all the displayed text to the language of my own country. After compiling and reinstalling the firmware, the text cannot be displayed correctly.

### Reproduction

For example, I directly modified the applications/main/bad_usb/application.fam name="Bad USB" Bad USB text and recompiled and installed the firmware and it could not be displayed on the device.
![234465742-f9e4d8b9-5518-4f79-814c-63a1aaa55ab3](https://user-images.githubusercontent.com/29472751/235068742-c07204d6-62a2-4a54-ac86-87b0a187d006.jpg)

**Comment by ClaraCrazy** [comment]
ofc. bc the firmware doesnt even have chinese symbols. it only has latin characters, so you gotta deal with those. And thats not a bug. Its just how it is
