### ISSUE TITLE
crash after playing tanks game

### ISSUE THREAD

**Issue by HUnde125** [ClaraCrazy/Flipper-Xtreme#223]
### Describe the bug.

At first i want to say that this firmware is very nice and helps me very much but i found a little bug, when you play the tanks game and you loose the flipper crashes 

### Reproduction

-

### Target

-

### Logs

```Text
-
```

### Anything else?

-

**Comment by ClaraCrazy** [comment]
aaand we stillnproduce firmware, not apps. Tell the author of that app
