### ISSUE TITLE
Mute/unmute flipper with one click

### ISSUE THREAD

**Issue by rhl2401** [ClaraCrazy/Flipper-Xtreme#224]
### Describe the enhancement you're suggesting.

I like to have the Flipper make sounds while interacting with it, but sometimes the sounds are really not appropriate (especiallialy places where they are very audible). 

It would be nice to be able to click on the volume bar in the notification area to mute/unmute the device altogether. Today, you must click "down" 20 times while having it make 20 beeps on different volume levels until it's completely silent. 

### Anything else?

You could always make the device remember the latest volume setting and restore to that one, but that is not really a concern for me. The ability to go from 100% to 0% and back to 100% would do the trick for me.

**Comment by Willy-JL** [comment]
Already exists in dev branch

**Comment by rhl2401** [comment]
Fantastic. I didn't realize steath mode included this feature. Thank you for your work!
