### ISSUE TITLE
Firmware Internal flash full

### ISSUE THREAD

**Issue by Lvxias** [ClaraCrazy/Flipper-Xtreme#233]
### Describe the bug.

After the last update I’ve noticed that the internal flash ok the flipper have become smaller and full. Now is 25 KB / 29 KB.

### Reproduction

Go on Flipper App or on storage info on Flipper.

**Comment by Willy-JL** [comment]
delete all files on internal that are not the u2f keys, or the notification settings. you shoudl onyl have those 3 files on internal. yes, internal storage is running out, but this is normal, not a bug

**Comment by ClaraCrazy** [comment]
thats... not a bug. thats how updates work. they get bigger, therefore space gets less.
