### ISSUE TITLE
cannot update to 0046 - Error need more free space in - internal storage

### ISSUE THREAD

**Issue by TheMany172** [ClaraCrazy/Flipper-Xtreme#237]
### Describe the bug.

Error
Need more free space in - 
internal storage

### Reproduction

downloaded 0046 via https://github.com/ClaraCrazy/Flipper-Xtreme/releases/tag/XFW-0046_06052023

was updating from 0045 (after hotfix)

copied accross from computer using qflipper

browse to update on flipper and press run in app

![signal-2023-05-06-201016](https://user-images.githubusercontent.com/110791742/236642455-c31a7d91-332d-48e8-ab4b-850d3fc86967.jpeg)

**Comment by Willy-JL** [comment]
what files do you have on internal storage?

**Comment by TheMany172** [comment]
Not too sure tbh - I have never added anything to it. When I check via qflipper it comes back with just some hidden files
![image](https://user-images.githubusercontent.com/110791742/236642623-22c89286-f12a-492f-aa30-3d26cef8d98b.png)

**Comment by Willy-JL** [comment]
yeah... RM moment... delete dt settings, passport settings, and if still not working delete region data too.

only needed files are the u2f ones and notification settings, region data if you care about region lock, remove if you want

**Comment by TheMany172** [comment]
Ah ok - so an issue due to me previously having RM as firmware then? thats a shame

**Comment by Willy-JL** [comment]
well, those files are there (mainly passport settings) because of RM, then our firmware is getting too big, so it cant fit those files + our firmware. xtreme doesnt use those, so just delete them

**Comment by TheMany172** [comment]
Np - I deleted the first two you said (bt settings, passport settings) but it still wouldnt, so also removed region data
ran update - it did a flipper has crashed null point reset blah
ran again - all good

Thanks Willy, glad its just an unrelated issue
