### ISSUE TITLE
Cannot Toggle BT in BadKB Macos Demo

### ISSUE THREAD

**Issue by aancw** [ClaraCrazy/Flipper-Xtreme#238]
### Describe the bug.

When changing the connection to BT, it will always reset to USB and cannot change the connection to BT. This is only affect demo macos. All demo is working as expected.

### Reproduction

1. Open BadKB
2. Choose demo_macos
3. Click Config
4. Change connection to BT

**Comment by ClaraCrazy** [comment]
not a bug. read the wiki. its made for usb. smh
