### ISSUE TITLE
external cc1101 problems

### ISSUE THREAD

**Issue by FoxLy1312** [ClaraCrazy/Flipper-Xtreme#240]
### Describe the bug.

external cc1101 Module dos not work when entering app from Fav. button

also dos not work in weather app

### Reproduction

1

° ajust favorit button as subghz 
° press fav button
° select settings external module
                ?
° no module found
° try again

2 

° open subghz via ui
° select external Module
° test (works)
° close and open via favorit-button
                ?
° module said internal 

### Anything else?

thx all <3

**Comment by iter8tor** [comment]
I tried it on 0046 and it works, from both fav and weather app.

**Comment by FoxLy1312** [comment]
Ok in that case i try a clean install

**Comment by FoxLy1312** [comment]
Fresh install dos the trick 🫡
