### ISSUE TITLE
Flipper wear os app

### ISSUE THREAD

**Issue by Barakine** [ClaraCrazy/Flipper-Xtreme#242]
### Describe the bug.

On watch you can click emulate to the flipper but you need the phone be synced to the flipper first
In the watch its stuck on waiting for connection 

### Reproduction

1. Download flipper for android and wear os
2. Sync phone and flipper
3. Open flipper on wear os
4. Keep loading for eternity 

### Anything else?

Also if it possible to emulate the saved nfcs file from the flipper with the smart watch?
Would be cool to save there your work tag and be able to enter work with your watch

**Comment by ClaraCrazy** [comment]
Not related to firmware
