### ISSUE TITLE
Missing DolphinDeeds on compile

### ISSUE THREAD

**Issue by leedave** [ClaraCrazy/Flipper-Xtreme#247]
### Describe the bug.

Hi There

Just compiling some apps for compatibility with your Firmware. I noticed a game had problems compiling because some DolphinDeeds from the OFW seem to be missing in Xtreme

- DolphinDeedPluginGameStart
- DolphinDeedPluginGameWin

### Reproduction

1. Download the source for the game color_guess
2. Add to folder applications_user
3. Compile using fbt

**Comment by Willy-JL** [comment]
We removed those because it makes little sense to give you xp when you play a game. It’s a pentesting device, we made it give xp when you use hacking apps. Just remove those lines before compiling if you want to do it yourself
