### ISSUE TITLE
bluetooth not staying conected

### ISSUE THREAD

**Issue by seeingoblivion** [ClaraCrazy/Flipper-Xtreme#249]
### Describe the bug.

When using Bluetooth remote, when doing a fresh connection, it works perfectly, but when exiting completely, not just choosing a different function. it and the computer will say still connected, but will not work again unless re-paired. 

### Reproduction

Pair flipper to computer (control not regular)
Enter Bluetooth remote
Works fine
Exit to menu and choose different function, works fine
Exit Bluetooth remote completely , and reenter
Will reconnect, but will not work on any function
Then unpair and forget connection
Then reconnect and works fine again

### Target

latest release

**Comment by Willy-JL** [comment]
fixed in dev branch

**Comment by seeingoblivion** [comment]
Ah perfect, thanks for the quick response!

**Comment by ClaraCrazy** [comment]
fixed in release
