### ISSUE TITLE
Learning new IR remote always open “raw” mode. 

### ISSUE THREAD

**Issue by Przemekmac1** [ClaraCrazy/Flipper-Xtreme#250]
### Describe the bug.

When I go infrared/learn new remote it will open app for learning in raw mode, also when I selected normal mode. 

### Reproduction

1. Switch on
2. Go IR/learn new remote (non-raw).

**Comment by ClaraCrazy** [comment]
lmao. how tf did we fuck that up? consider it fixed next release

**Comment by Willy-JL** [comment]
After looking into it, this is intended behavior. Learn remote raw disables trying to decode the signals, while learn remote keeps decoding enabled. Thing is, if the IR samples it picks up in normal learn remote do not correspond to any known protocol it knows how to decode, it still picks them up as raw. Learns raw simply stops it from *trying* to decode
