### ISSUE TITLE
Update #046 failed

### ISSUE THREAD

**Issue by 8um1c4** [ClaraCrazy/Flipper-Xtreme#252]
### Describe the bug.

When trying to update from 45 to 46 via web, I get the following message:
Update Failed!
Error #[1-20]

Any help? 

### Reproduction

I've tried 4 times.

**Comment by Willy-JL** [comment]
what files do you have on internal storage? (enable hidden files in qflipper)

**Comment by 8um1c4** [comment]
Only 5 small files. Probably there are files hidden. Can you please help how do I un-hidden them?

**Comment by Willy-JL** [comment]
Its not about the files being small. I asked what files you see, 5 files sounds normal, mind telling me what they are?

**Comment by Willy-JL** [comment]
delete all of em then retry. maybe keep dolphin state if you want, others are fine to lose (just small setting options)

**Comment by 8um1c4** [comment]
Solved ! Many thanks Willy-JL! Never happened before!
Regards
