### ISSUE TITLE
Crashes when exiting CLI (subghz chat)

### ISSUE THREAD

**Issue by Kuolinisku** [ClaraCrazy/Flipper-Xtreme#256]
### Describe the bug.

When you exit the CLI application initially it is fine, and you can also back out to the apps menu, but when you hit back for a 3rd time to return to the home screen it crashes with a "NULL pointer dereference" error.  

### Reproduction

1. Go to Apps > Tools > CLI (subghz chat)
2. Launch the app
3. Long-press the BACK button to exit
4. Press the BACK button to go back to the Apps menu
5. Press the BACK button to go back to the home screen
6. This is where the error should occur if it behaves the same as mine is

### Anything else?

Fairly minor issue - it recovers immediately from the crash and you were exiting everything anyway - but annoying for people who use the app probably.

**Comment by Willy-JL** [comment]
Fixed in dev branch

**Comment by Kuolinisku** [comment]
Thanks!  

Is there a spot I should have checked for that?  I did skim the existing bugs but that is all I checked.  Anyway good to know it is fixed.

**Comment by Willy-JL** [comment]
well in this case it wasn't reported by a user so its not in an issue, nano (from unleashed) informed us and gave a fix for it. it is listed in the projects tab in the done column tho

**Comment by ClaraCrazy** [comment]
fixed in release
