### ISSUE TITLE
App and bluetooth not working

### ISSUE THREAD

**Issue by luqezr** [ClaraCrazy/Flipper-Xtreme#257]
### Describe the bug.

Hi All, since i’ve installed this firmware i’ve lost the ability connect via bluetooth to the flipper with the app to controle it remotely.
If I activate bluetooth my device wont show up, I've tried with iOS, android, windows and linux but nothing :(.

If I use the badusb via bluetooth it works, but thats the only bluetooth feature i can use, could it be that this affects the normal bluetooth use?

I've reinstalled the firmware a few times

### Reproduction

1 open bluetooth
Flipper zero wont show up, but honestly there is no error sign

**Comment by Willy-JL** [comment]
you need to use the flipper mobile app to pair

**Comment by luqezr** [comment]
> you need to use the flipper mobile app to pair

Hi Willy, thanks for the quick reply, it worked! 
It synchronizes, but if I try to emulate something from the app my flipper doesnt do anything

**Comment by Willy-JL** [comment]
already working on a fix for that, mind pinging me in the discord so i can add you to the ticket?

**Comment by luqezr** [comment]
> already working on a fix for that, mind pinging me in the discord so i can add you to the ticket?

Hi willy, sure, i'll do that :)

**Comment by Willy-JL** [comment]
confirmed fixed in dev branch via discord, will be in next release

**Comment by sariyan-0** [comment]
Same i have the same problem 😕

**Comment by Willy-JL** [comment]
> Same i have the same problem 😕

Well read the messages above. 1: it won’t show in Bluetooth, it shows in the mobile app. 2: emulating might not work, and this is fixed in dev branch and will be in next release

**Comment by ClaraCrazy** [comment]
fixed in release
