### ISSUE TITLE
Save remote from Universal Remotes

### ISSUE THREAD

**Issue by Zarcolio** [ClaraCrazy/Flipper-Xtreme#266]
### Describe the enhancement you're suggesting.

Currently, when using Universal Remotes, it just fires all remotes in succession in order to get the desired result. But there's no way of saving a successful result.
So what I'd like to propose, is to add an option to save from Universal Remotes. Select a brand (if possible), show a "Save" button and fire the commands with a small pause at the end. If the desired result has taken place, the user can hit the "Save" button and save it with the other saved remotes. 

### Anything else?

No, that was it 😇

**Comment by ClaraCrazy** [comment]
would only slow down the operations by a lot, and be uselessly complex to add
