### ISSUE TITLE
Latest Firmware not installing with 'Flipper Xtreme'

### ISSUE THREAD

**Issue by Retaliation357** [ClaraCrazy/Flipper-Xtreme#272]
### Describe the bug.

As im flashing the new update towards the end a message on the flipper pops up saying 'Update Failed Error #[1-20]. Not sure if i missed a step

### Reproduction

Updating firmware

**Comment by ClaraCrazy** [comment]
that means your internal storage is full. remove all files besides the u2f key from it. nothing else should be there
