### ISSUE TITLE
The new web updater is unreachable

### ISSUE THREAD

**Issue by InToSSH** [ClaraCrazy/Flipper-Xtreme#274]
### Describe the bug.

I noticed starting v47 you are using a new web updater `https://flipper-xtre.me/update`. 
It is unfortunately unreachable with an error from Cloudfront `Error code 523`

### Reproduction

1. Go to realeases
2. Release v47
3. Click Web updater (Chrome)
4. See Cloudflare error

**Comment by Willy-JL** [comment]
yes, the web hosting is down due to power outages in some datacenters. just have to wait a bit

**Comment by InToSSH** [comment]
That was a super fast response. Thank you, I will wait 😄 I won't close it just now so others can see it in case they have the same question.

**Comment by ClaraCrazy** [comment]
back
