### ISSUE TITLE
Problem with Flipper zero Light 

### ISSUE THREAD

**Issue by Khl200** [ClaraCrazy/Flipper-Xtreme#276]
when i installed the latest Xtreme Firmware ,the light is gone ..
everything works but no screen light is on ..

**Comment by Willy-JL** [comment]
You enabled the rgb backlight without having installed the backlight mod. Disable this option in xtreme settings > misc > rgb backlight

**Comment by Khl200** [comment]
thanks a lot my friend ..
it works like you said ..
and thanks to Clara for making it 
Danke
