### ISSUE TITLE
After installing the new update Flipper Zero just doesn't work anymore

### ISSUE THREAD

**Issue by jaochoo** [ClaraCrazy/Flipper-Xtreme#278]
### Describe the bug.

After installing the new update (downloaded .tgz and install via qFlipper) 
Flipper Zero is unable to connect to the computer, screen entirely shut off 

Tried to force restart (left+back button) the light flashes but nothing changed.

Please do help me.

### Reproduction

1. Update the version with .tgz file via qFlipper
2. version updated
3. Flipper immedeatly bricked

**Comment by jaochoo** [comment]
after leaving it for couple of minute, I tried force reboot again, this time it went to Update&Recovery Mode: DFU started

**Comment by Willy-JL** [comment]
do you happen to have a devboard? would be useful to see some logs

**Comment by jaochoo** [comment]
After recovery, the official firmware was installed. I think I will try to install the update again.

**Comment by Willy-JL** [comment]
yeah, that was what i was gonna tell you to do after you gave some logs if possible. dont think you can get logs withthose boards, so then just go ahead and reinstall. might want to also use the repair option in qflipper (go into dfu mode and plug in then) before reinstalling xtreme

**Comment by jaochoo** [comment]
@Willy-JL Thank you for your assistance, anyway!

**Comment by jaochoo** [comment]
The update installation was completed and my Filpper now works fine. I suppose it was an error on my side. Sorry for the inconvenience. I will close the issue now.
