### ISSUE TITLE
Keelog versus Cnt

### ISSUE THREAD

**Issue by 8um1c4** [ClaraCrazy/Flipper-Xtreme#284]
### Describe the bug.

Iºm trying to reproduce a KeeLoq signal, but the cnt counter doesnºt increment.
In the file I donºt see where to store or change the cnt value. Is it a bug or a feature?

### Reproduction

Yes, sending signal.

**Comment by ClaraCrazy** [comment]
Hey there!

This happens if the manufacturer is not known. In that case we obviously cant generate new packets to send, and cant increment any counter. 

Having support for keeloq in general does not mean we can use every keeloq signal that exists, sadly.

**Comment by 8um1c4** [comment]
But Iºve keelog signals recorded that have associated the counter and increase it. I donºt see where is it stored... Can you help?
