### ISSUE TITLE
Flipper is not visible in iPhone Bluetooth

### ISSUE THREAD

**Issue by T0X1Cx** [ClaraCrazy/Flipper-Xtreme#288]
### Describe the bug.

I can't see my Flipper Zero on iPhone 11 after installing the latest update.

### Reproduction

1. Update last release

**Comment by Willy-JL** [comment]
not in bluetooth settings. use the flipper mobile app

**Comment by ndases** [comment]
Same case here... even using the mobile app directly
![flipper_bt_issue](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/54564395/bb0bec7e-4b8e-43e5-b772-10e976558580)

**Comment by Willy-JL** [comment]
no, that is a completely different issue. you came from a previously paired mobile app and installed a recent xtreme. with v47 and v48 the bluetooth code changed, you need to pair again. forget flipper both in your phone's settings and from the mobile app, and also on flipper from settings > bluetooth.

**Comment by ndases** [comment]
Thanks mate, worked fine
