### ISSUE TITLE
windows computer will not show flipper zero as bluetooth device when trying to use Bad KB

### ISSUE THREAD

**Issue by EllieEx** [ClaraCrazy/Flipper-Xtreme#289]
### Describe the bug.

Device shows on iphone but will not show on computer even when i try using it as a bluetooth controller in the remote app nothing shows

### Reproduction

1. turn on
2. open Bad KB foler
3. pick ducky file
4. wait for connection to start
5. NOTHING EVER SHOWS TO CONNECT TO

### Target

need to be able to connect to windows laptop via bluetooth

**Comment by ClaraCrazy** [comment]
shows fine for 6k+ people in discord and the 200k people that use the fw. sounds like a skill issue to me

**Comment by EllieEx** [comment]
i figured it out, laptop doesn't support bluetooth (BLE) i'll have to get a bluetooth dongle

**Comment by ClaraCrazy** [comment]
yeet.
