### ISSUE TITLE
XFW-0048_03062023 | SubGHz Main Menu Hang

### ISSUE THREAD

**Issue by undertuga** [ClaraCrazy/Flipper-Xtreme#293]
### Describe the bug.

After updating Flipper Zero with the version XFW-0048_03062023 of the Xtreme firmware, the SubGHz main menu does not open, and also hangs the device (sometimes for a few seconds, but others it requires a restart / reboot.

### Reproduction

1. Update Flipper Zero firmware from XFW-0047_29052023 to XFW-0048_03062023
2. Go to the main menu
3. Try to access the SubGHz menu

**Comment by ClaraCrazy** [comment]
Unable to replicate. Both staff and the 6k users in the discord are unable to get this to happen, let alone the over 100k that download this firmware. 

I'd say your best bet is to just restart the flipper
