### ISSUE TITLE
Widget use on iOS

### ISSUE THREAD

**Issue by Apok76** [ClaraCrazy/Flipper-Xtreme#295]
### Describe the bug.

When I add a widget from the "Flipper" App. It doesn't work right. Syncing becomes impossible and Widgets do not work at all.

### Reproduction

1. On the iPhone in the Flipper App, tap "Options".
2. On the iPhone tap "Widgets".
3. On the iPhone add a widget.
4. On the iPhone go back to the main menu.
5. On the iPhone tap "Synchronize". It never does.
6. On the iPhone scroll to the "Widgets" section. You will see it has not added anything.

**Comment by ClaraCrazy** [comment]
not firmware related
