### ISSUE TITLE
Sub-GHz Spectrum Analyzer

### ISSUE THREAD

**Issue by analyserdmz** [ClaraCrazy/Flipper-Xtreme#307]
### Describe the enhancement you're suggesting.

It would be convenient if the Sub-GHz Spectrum Analyzer could automatically save what it detects, instead of just reporting the detected ones.

### Anything else?

It could auto-save the detected signals with a human-readable timestamp as a filename or something like that. eg. "2023-19-06_15-42_433.000".

**Comment by ClaraCrazy** [comment]
if you set it manually, thats your problem for not just hitting OK

**Comment by analyserdmz** [comment]
You can't hop through all modulations in the reader.
