### ISSUE TITLE
BADkb favorites Pt2

### ISSUE THREAD

**Issue by Retaliation357** [ClaraCrazy/Flipper-Xtreme#308]
### Description of the feature you're suggesting.

In the latest firmware I know there is an option to Favorite/Pin actions like badkb payloads, folders, etc. There should also be an option to Pin certain payloads in folders for Badkb to the top instead of having to search for a specific payload. So if i have a folder with 10 payloads, Id have an option to hold down the OK button for a 3s on a single payload and be able to pin it to top with a little pin icon at the end of the title of the payload. Im referring to that functionality being added into badkb itself. Because I already have a bunch of other things added to my favorites from different apps. So my favorites/pins are already a mess itself and I was thinking about it being added into the other apps separately as well so it can be more organized.

**Comment by ClaraCrazy** [comment]
no, there shouldnt. What you need is organise your folders properly, not a secondary favorite function
