### ISSUE TITLE
BadKB: Bluetooth not working

### ISSUE THREAD

**Issue by lRoberth** [ClaraCrazy/Flipper-Xtreme#309]
### Describe the bug.

The device does display on nearby BT devices, but on connected, the screen shows "Connect to a device". If I click Run, it stays on "Will run on connect. It's like it is transmitting the BT connection from FZ to devices, but FZ is not responsive when a connection is established. Tried it on a laptop and iPhone.

### Reproduction

1.- Open BadKB
2.- Load file
3.- Go left for config
4.- Set connection BT
5.- Set a random device name
6.- Clicked Randomize BT MAC
7.- Successfully connect device to FZ BT connection
8.- Script cannot be executed as FZ says there's no connection

### Target

iPhone

**Comment by Willy-JL** [comment]
Fixed in dev branch

**Comment by lRoberth** [comment]
> Fixed in dev branch

Sounds great ,thank you. Also I think I found a sort around. If you go back to script selection, and select it again, it now detects the BT connection and the script runs successfully.

**Comment by Willy-JL** [comment]
yes, thats exactly whats fixed in dev branch. along with a huge rework of badkb as a whole
