### ISSUE TITLE
Limited space for custom applications

### ISSUE THREAD

**Issue by viifirm** [ClaraCrazy/Flipper-Xtreme#313]
### Describe the enhancement you're suggesting.

Dear Developers, I found that when i try to add more custom applications, the STM32 chip didn't have enough space for it. the complied file size will be more than 800K. When i try to remove some image assets or games to make some space, it seems still will fetch content from github and compile the deleted content into the firmware. Please if you could quick point out for me that how to make the modification to the source code taking effect. Thanks.

**Comment by Willy-JL** [comment]
You use external apps, not internal. You leave internal storage to firmware.
