### ISSUE TITLE
Morse code SubGhz Receiver/Sender

### ISSUE THREAD

**Issue by xAstroBoy** [ClaraCrazy/Flipper-Xtreme#318]
### Description of the feature you're suggesting.

Just a small idea, since the SOS app for subghz with morse code is a cool feature, maybe the app should be able to both receive and decode morse code (with the option to see it raw) and send it as well from a text editor, including a few pre-made messages like S.O.S and such.

**Comment by ClaraCrazy** [comment]
thats literally just the subghz chat but in annoying...

**Comment by ClaraCrazy** [comment]
theres a reason why I declined the sos app in the first place, so adding more to a declined idea wont go anywhere

**Comment by xAstroBoy** [comment]
> theres a reason why I declined the sos app in the first place, so adding more to a declined idea wont go anywhere

oh, i just saw the #182  and thought it was a cool feature.
