### ISSUE TITLE
Sound Still Plays

### ISSUE THREAD

**Issue by Ghdhdhdh** [ClaraCrazy/Flipper-Xtreme#319]
### Describe the bug.

When I turn off sound by clicking up on the home screen and turning the volume to 0,  the volume in games is still apparent, but not in apps list NFC

### Reproduction

1. Turn on the flipper
2. turn the volume to 0
3. Launch Doom

### Target

N/A

### Logs

```Text
Not Needed
```

**Comment by Willy-JL** [comment]
complain to the app developers that dont respect how sound works everywhere else on flipper. we dont make those apps

**Comment by Ghdhdhdh** [comment]
> complain to the app developers that dont respect how sound works everywhere else on flipper. we dont make those apps

Thanks, Thought it was the firmware.
