### ISSUE TITLE
RPC error in command 'system.update': ERROR_INVALID_PARAMETERS

### ISSUE THREAD

**Issue by Louis-Beke** [ClaraCrazy/Flipper-Xtreme#320]
### Describe the bug.

if i try to update i get this error RPC error in command 'system.update': ERROR_INVALID_PARAMETERS

### Reproduction

uses https://flipper-xtre.me/update/

**Comment by Willy-JL** [comment]
Close qflipper

**Comment by Louis-Beke** [comment]
dont have

**Comment by Willy-JL** [comment]
Try installing with the qflipper method then

**Comment by Louis-Beke** [comment]
errors [UTL] Start Update @Louis ERROR: Internal storage is full
[DEV] Full Update @Louis ERROR: Internal storage is full

how can i clean it

**Comment by Willy-JL** [comment]
go to files tab, internal flash, enable hidden files, delete everything (keep the .u2f files if you have them and use u2f)
