### ISSUE TITLE
New updates do not work on new mobile app

### ISSUE THREAD

**Issue by charlieporth1** [ClaraCrazy/Flipper-Xtreme#324]
### Describe the bug.

Update from 47-49 do not update with the mobile app on Android. I don't know about iOS but can test if if requested.
![Screenshot_20230705_112947_Flipper](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/13573364/be347cbf-88fa-4f06-adf6-79793f5ba521)
![Screenshot_20230705_113320_Settings](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/13573364/305bef7b-8df0-4e6d-8e51-a22e62d3844b)
Also understand this is a low priority item. There are work around with the web interface 

### Reproduction

Try and update Xtreme via mobile app

### Target

49

**Comment by ClaraCrazy** [comment]
Works fine here, not an issue with the firmware regardless.
