### ISSUE TITLE
NFC & RFID errors appeared after commits on Jul 14

### ISSUE THREAD

**Issue by cokyrain** [ClaraCrazy/Flipper-Xtreme#329]
### Describe the bug.

Can't enter the main menu of NFC & RFID . It's no exception before commits on Jul 14.
![Screenshot-20230714-154648](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/75012356/0a2b1a28-4e5b-488e-a802-2edce117c1e7)
![Screenshot-20230714-154658](https://github.com/ClaraCrazy/Flipper-Xtreme/assets/75012356/f6d6a227-0bb2-4adb-9513-d1d9b6889887)

### Reproduction

Compiled on ubuntu, 
[`Firmware here`](https://github.com/cokyrain/FlipperZeroFirmware/releases/tag/20230714-Xtreme)
[`Compiled here`](https://github.com/cokyrain/FlipperZeroFirmware/actions/runs/5551594930/jobs/10137906272)

**Comment by Willy-JL** [comment]
It’s a dev branch. It’s not stable. We’re aware of this, it’s a work in progress for mergin the changes from upstream that reworked how apps work
