### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by hhgregg33** [ClaraCrazy/Flipper-Xtreme#35]
### Describe the bug.

Evangelion_Exp.txt kicks you back to Music Player.

### Reproduction

1. select Evangelion_Exp.txt
2. kicks you back to Music Player 
3. repeats

### Target

Evangelion_Exp.txt

**Comment by jbohack** [comment]
hello! thanks for the bug report :) this seems to be a broken file between multiple firmwares. i will give this a check and will try to repair it!
