### ISSUE TITLE
Missing Credits?

### ISSUE THREAD

**Issue by ankris812** [ClaraCrazy/Flipper-Xtreme#37]
### Description of the feature you're suggesting.

If you are going to take Code from other people, why dont you give credits? The gpio and ir replication is from my firmware.

**Comment by ClaraCrazy** [comment]
I have no idea what makes you think I took code from you, since I have literally never heard of you... not to mention that after a quick glance your two flipper forks don't even have unique commits, but uh... sure buddy!

**Comment by ankris812** [comment]
If It wasnt you, then it was Roguemaster. Sorry if its the case.

**Comment by ClaraCrazy** [comment]
No, actually lets keep this open. I'm not the only one working on this and maybe should take that into account too. My points stand but feel free to link your code so I can handle this if that's true

**Comment by ClaraCrazy** [comment]
Dont want any negative views here. If its yours, drop a link and I'll have it handled asap

**Comment by ankris812** [comment]
Sure. Just let me find when i made the commit. And just as a note. Signal replication doesnt work correctly on the subghz part. Signal output is a bit distorted.

**Comment by ClaraCrazy** [comment]
Thanks, and noted. Might have one of my devs look over it perhaps

**Comment by ankris812** [comment]
Also you have this https://github.com/ankris812/Yggdrassil/commit/f8aa139b117c3f9db89a60892eafb1ef02a0f26e If you want to add It to the resources.

**Comment by ClaraCrazy** [comment]
Good to know where those came from. Only downloaded them from a discord lol

**Comment by ankris812** [comment]
Lately I don't have time for my firmware, but if it's not a bother, I think I'll collaborate from time to time with this firmware, it fits exactly what I want to do with mine, something more advanced and functional, but that it remains stable.

**Comment by ClaraCrazy** [comment]
sure sure. would be nice if you'd join the discord then and we can welcome you to the dev team... so we are on track with all stuff

and I'd still need that commit for credits

**Comment by ankris812** [comment]
> Good to know where those came from. Only downloaded them from a discord lol

Oh, not all are mine, we just made files for more frequencies that werent available at that time

**Comment by ankris812** [comment]
> sure sure. would be nice if you'd join the discord then and we can welcome you to the dev team... so we are on track with all stuff
> 
> and I'd still need that commit for credits

When i find It. A couple of days ago I merged it with the original branch and I don't know where it is now.

**Comment by ClaraCrazy** [comment]
lol
