### ISSUE TITLE
ability to be able to build without 'nsfw' gfx

### ISSUE THREAD

**Issue by gerryk** [ClaraCrazy/Flipper-Xtreme#46]
### Description of the feature you're suggesting.

I like what you are doing with this fork, esp. the tidying up of code form various upstream repos. However, not interested in the animations & non-standard gfx. SFW options doesn't replace all graphics. An option to build with just stock images/animations would be welcomed.

**Comment by ClaraCrazy** [comment]
SFW will replace all graphics and texts in the next update, which is in testing rn. I'd join the discord for live updates and questions / suggestions
