### ISSUE TITLE
Subghz remote freezes with jam

### ISSUE THREAD

**Issue by Hyakke1** [ClaraCrazy/Flipper-Xtreme#48]
### Describe the bug.

I made a subghz remote for my lights and added jam freq 433.92 the jam does work but it gets stuck and requires a restart. 

### Reproduction

1. Open subghz remote
2. open remote with jam
3. hit the jam button

### Logs

```Text
Logs do not show anything but the reboot.
```

### Anything else?

here is the text to make a remote to recreate this.

Filetype: Flipper SubGhz RAW File
Version: 1
UP: 
DOWN:
LEFT: 
RIGHT: 
OK: /any/subghz/Jamming/Jam_433.92.sub
ULABEL: 
DLABEL: 
LLABEL: 
RLABEL: 
OKLABEL: JAM

**Comment by ClaraCrazy** [comment]
Cant replicate
