### ISSUE TITLE
Jamming Files

### ISSUE THREAD

**Issue by kevtheskin** [ClaraCrazy/Flipper-Xtreme#50]
### Describe the bug.

Hello there, Sorry to hassle you. I have updated my flipper fw to your Xtreme from unleashed. For some reason I cannot find the jamming files? Can you please guide me to the location in the flipper.
Cheers and thanks for all your work . Happy New Year from Scotland. Kev

### Reproduction

Searched Subghz saved folder and application tools,misc

**Comment by ClaraCrazy** [comment]
They are right there in subghz/jamming...
