### ISSUE TITLE
Resolution issue?

### ISSUE THREAD

**Issue by Phaneron1991** [ClaraCrazy/Flipper-Xtreme#541]
### Describe the bug.

Just updated and now all the text is smushed and tiny and there's a boarder around the screen

### Reproduction

1. update
2. look at text
3. ???
4. smol txt lol

### Anything else?

Just minor cosmetics lol, Thank you all for your hard work and I sincerely hope you've had a good start to the new year and a great year to come!!

**Comment by WillyJL** [comment]
Show a screenshot

**Comment by Phaneron1991** [comment]
My B, sorry

Screenshots for context



![Screenshot-20240202-125323](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/52024784/ee2e778e-999a-4a09-821b-0ab242dee5eb)

![Screenshot-20240202-125311](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/52024784/a31cb740-a3c0-4e25-ad27-6306ce3b8258)

**Comment by WillyJL** [comment]
You have the watchdogs asset pack enabled. As per the changelog in v53, watchdogs now has custom fonts. These are the watchdogs themed fonts. Disable watchdogs asset pack if you don't want this.

**Comment by Phaneron1991** [comment]
aah thanks, sorry for the confusion

**Comment by breaky2023** [comment]
I tend to Read everything in which case I knew the Text would be the way it is when WatchDogs is enabled, not just download! - Don't mean to sound harsh but I am just open ;)  

Great Work Willy-JL and all the team 👍
