### ISSUE TITLE
read bank cards

### ISSUE THREAD

**Issue by KaliStudio** [ClaraCrazy/Flipper-Xtreme#543]
### Description of the feature you're suggesting.

Add credit card reading like version flipperzero-firmware-0.62.1 did
[flipperzero-firmware-0.62.1.zip](https://github.com/Flipper-XFW/Xtreme-Firmware/files/14159242/flipperzero-firmware-0.62.1.zip)

**Comment by WillyJL** [comment]
it was always there, temporarily removed in v52, and its back in v53. update.

**Comment by KaliStudio** [comment]
oops thanks I hadn't seen the update
