### ISSUE TITLE
MF dictionary additional keys

### ISSUE THREAD

**Issue by SarenKing** [ClaraCrazy/Flipper-Xtreme#546]
### Description of the feature you're suggesting.

I found some keys that are not included in the file.
Source: https://firefart.at/post/how-to-crack-mifare-classic-cards/    (Tag1-2-3 mfd dumped file.) 
imported / converted file to MCT , and checked. 
New Keys: 
5281A048E648
6288EB61EEDD
C917CB115EC9
AAE82E15143A
97CF50CE9BB3
A7439DBB4024
FD2D7B288E3E
E157D45486A1

**Comment by WillyJL** [comment]
from the article you linked:

> After examining other tags for the same vending machine I noticed that these all have different keys. It seems like the vending machine calculates the keys based on the tags unique UID or something else to add an extra layer of security. So far I have not managed to crack the scheme. If you manage to derive the key from the captures below please contact me so I can verify it with other tags.

> I put some dumps here for download if you want to investigate the key derivation scheme:

these keys are derived from the individual tags, they won't work on other tags of the same system. for that reason, including them is actually counter productive since they will work on no other tags, and instead take up time in the bruteforce process.
