### ISSUE TITLE
Infrared GPIO autodetect

### ISSUE THREAD

**Issue by X3r0C00L** [ClaraCrazy/Flipper-Xtreme#547]
### Describe the bug.

IR GPIO autodetect is set to on by default. Thus if you have a flux capacitor inserted. It automatically thinks that is an IR blaster and tries to send to it. I had to go in and manually set it back to internal. 
Setting this to off by default would be great. 

### Reproduction

Have flux capacitor plugged in
open IR
select tv
press ok on power
flux capacitor leds start blinking IR doesnt work. 
Turn off the auto detect and all goes back to normal.

**Comment by WillyJL** [comment]
while you make a valid point, i feel like its a pretty 50/50 tradeoff on having it on/off by default. on by default, your blaster works out ot of the box but it triggers with flux. off by default, your blaster needs to be configured, but it doesnt trigger with flux.

overall i consider the advantage of autodetect to be greater, so i think it should stay on by default
