### ISSUE TITLE
Sub-ghz: not available

### ISSUE THREAD

**Issue by LinkseRat** [ClaraCrazy/Flipper-Xtreme#550]
### Describe the bug.

I installed the new update and at first everything worked fine. But when i tried to open the sub-ghz tab again, the FZ crashed. 
I restarted the FZ and i can use everything except the sub-ghz app. After that first try it's unusable

### Reproduction

1. update the firmware
2. restart FZ
3. open sub-ghz
4. test features
5. exit sub-ghz
6. open sub-ghz
7. FZ crashes

**Comment by Sil333033** [comment]
it would help if you mention what the flipper says 🤡

**Comment by LinkseRat** [comment]
@Sil333033 
![IMG_20161201_135511](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/12091764/371b86bd-09dc-4553-9f9e-aae1f3ec2cf6)
here's a picture

**Comment by Sil333033** [comment]
this is already fixed in our dev branch. Update to a dev release or be patient for a new release

**Comment by WillyJL** [comment]
Duplicate of #548
