### ISSUE TITLE
Bug when trying to show intro

### ISSUE THREAD

**Issue by ghost** [ClaraCrazy/Flipper-Xtreme#551]
### Describe the bug.

You can't replay the XFW intro. It just reboots then crashes with error "NULL pointer dereference"

### Reproduction

1. Turn on
2. Go to Xtreme Settings
3. Go to Misc
4. Select Replay Xtreme Intro

### Target

XFW (Xtreme Firmware)

### Logs

```Text
not collected
```

**Comment by WillyJL** [comment]
cant reproduce, the file for it might have just been deleted or something. try reinstalling the firmware, if it still happens, try formatting the sd card then reinstalling again.

**Comment by ghost** [comment]
> cant reproduce, the file for it might have just been deleted or something. try reinstalling the firmware, if it still happens, try formatting the sd card then reinstalling again.

recently updated XFW and it worked fine
