### ISSUE TITLE
External app store

### ISSUE THREAD

**Issue by GhostService** [ClaraCrazy/Flipper-Xtreme#562]
### Describe the bug.

I have not installed XFW yet, because i want to be able to install apps from the flipper store. Is there a way to install or even sideload these apps to xfw?

### Reproduction

I have not installed XFW yet, because i want to be able to install apps from the flipper store. Is there a way to install or even sideload these apps to xfw?

**Comment by WillyJL** [comment]
...why would you make an issue before trying...?

the flipper app hub works. as long as youre on a stable release.
