### ISSUE TITLE
Flipper Zero App Store Not Working Because of Outdated Firmware

### ISSUE THREAD

**Issue by AbeNaws** [ClaraCrazy/Flipper-Xtreme#564]
### Describe the bug.

The Flipper Zero App Store on iPhone says that it is not compatible with my Firmware and that I need to install the latest version. I am running the latest firmware from the XWF dev channel.
![IMG_1053](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/113221023/de2c5ad8-2981-4e90-96df-a13214149cb7)

### Reproduction

Open Flipper App
Go to Hub -> Apps
You will see the not compatible message.

**Comment by WillyJL** [comment]
it is the same dance every month with every update.

ofw has updated api methods, api version changed.

but app hub is based on stable release api version, so apps are old for development firmware which is new.

when ofw releases next stable, it will work. stay on xfw stable or cope.
