### ISSUE TITLE
Does BLE Spam not work as well as it used to?

### ISSUE THREAD

**Issue by T0X1Cx** [ClaraCrazy/Flipper-Xtreme#578]
### Describe the bug.

For some time now I have noticed that BLE Spam does not work as well as it used to.

On Android, it just pops up once the notification and it doesn't pop up anymore or it doesn't pop up as often.

Has Android come out with a fix for this?

### Reproduction

BLE Spam

**Comment by xMasterX** [comment]
Some of the latest android versions has patches to fix ble notifications spam
This is not a bug and not related to the app
