### ISSUE TITLE
Discord captcha.bot not giving problem

### ISSUE THREAD

**Issue by super06** [ClaraCrazy/Flipper-Xtreme#590]
I try joining the discord but the captcha.bot doesn't give me a problem

From 4 different devices it still doesn't. I click "I am a human being" then i click answer but it just says "verify yourself This for will be submitted to captcha.bot ANSWRE*

And if I click "Click to see attachment" It just highlights the original "I am a mature human being

**Comment by ClaraCrazy** [comment]
jap, works for 31k people, just not for you. ofc. 

Not a bug, fix your client.

**Comment by super06** [comment]
Fix my client. I used all 3 fucking clients, web , Desktop, and stupid mobile app.

**Comment by super06** [comment]
> jap, works for 31k people, just not for you. ofc.
> 
> Not a bug, fix your client.

Fix my client. I used all 3 fucking clients, web , Desktop, and stupid mobile app. If your gunna gunna close the the issue might as well help me instead of being an ass
