### ISSUE TITLE
Thank you ClaraCrazy

### ISSUE THREAD

**Issue by super06** [ClaraCrazy/Flipper-Xtreme#591]
I've logged into a different account in discord and it works, any idea why it doesn't  on my main account. It works now after changing settings

**Comment by super06** [comment]
Liberal britch

**Comment by super06** [comment]
Liberal britch your like my sister and mother
Both horrible people.

**Comment by ClaraCrazy** [comment]
frfr ong no cap. so liberal imma let you use your own brain

**Comment by super06** [comment]
Your insecure

**Comment by super06** [comment]
Let me gess your next words are "ugh, you know what. I'm not gunna use any more brain power on this"  wait you where using brain power. Never would have guessed

**Comment by dav3shanahan** [comment]
You’re
