### ISSUE TITLE
Discord unban

### ISSUE THREAD

**Issue by masterhacka** [ClaraCrazy/Flipper-Xtreme#592]
### Description of the feature you're suggesting.

Hi my Discord token got hacked so someone spammed some trash with my account. I am sorry for that but changed the password so everything should be fine now. Is there any way you can unblock me?

**Comment by masterhacka** [comment]
Discord tag: xxcyanidexx

**Comment by ClaraCrazy** [comment]
the bot literally sent a dm with an appeal form. if you cant even use that, then no.

**Comment by masterhacka** [comment]
The bot tells me to wait one day so this is why I am asking here.

**Comment by ClaraCrazy** [comment]
if the bot tells you to wait one day... wait one day💀

**Comment by masterhacka** [comment]
Alright, thanks you anyway
