### ISSUE TITLE
Enable error

### ISSUE THREAD

**Issue by UTo4ka-etxt** [ClaraCrazy/Flipper-Xtreme#593]
### Describe the bug.

When launching some functions, the lock icon and the inscription “enable debug" are displayed. What should I do about it?

### Reproduction

1. Go to the “infrared" section. 2. Select the "debug rx" or "learn new remote raw" function

### Target

Fixing the problem

**Comment by ClaraCrazy** [comment]
you should.... *enable debug* as it tells you to. And if you dont know what that means or where it is, you shouldnt be touching it.
