### ISSUE TITLE
Crash when choosing a file for Evil Portal

### ISSUE THREAD

**Issue by 1Industries** [ClaraCrazy/Flipper-Xtreme#608]
### Describe the bug.

When choosing a file with both Evil Portal or Marauder, the Flipper crashes with the message "out of memory"

### Reproduction

1. Open Marauder
2. Press "Load HTML File"
3. Choose a file 
4. It crashes

**Comment by ClaraCrazy** [comment]
not a bug, read docs. error literally tells you too. Your file is too big
