### ISSUE TITLE
Firmware text overlaps with DFU recover mode header

### ISSUE THREAD

**Issue by PossibleScam** [ClaraCrazy/Flipper-Xtreme#61]
### Describe the bug.

`Update and Recover Mode DFU started` text overlapes the custom firmware text.

### Reproduction

1. Enter DFU mode on device running v35.

**Comment by PossibleScam** [comment]
Super low PRIO. Small polish thing. Nice FW though Overall. :)

**Comment by ClaraCrazy** [comment]
Known & fixed in the next release :)
