### ISSUE TITLE
NFC-A (TonieBox)

### ISSUE THREAD

**Issue by Xonic88** [ClaraCrazy/Flipper-Xtreme#68]
### Describe the bug.

Hello Dev. Team, 
i really like your Xtrem firmware, you are doing a great job. 
Since the last update, i can't read NFC-A tags for TonieBox anymore. 
Also, I can't emulate my saved ones anymore.
Are you currently working on it or do I have to look for another solution.

### Reproduction

Read Specific Card Type NFC-A as Toniebox not showing anymore.

### Target

Toniebox

**Comment by ClaraCrazy** [comment]
We know. some idiot (me) removed half the NFC code on accident. its back in the next release, as stated multiple times on our server. ETA: somewhen today
