### ISSUE TITLE
Long press 2 lock

### ISSUE THREAD

**Issue by WatskeBart** [ClaraCrazy/Flipper-Xtreme#72]
### Describe the enhancement you're suggesting.

Love the new feature long press 2 lock.
I suggest to move the long press 2 lock, from the **left** to the **right** button.

To quickly reboot the Flipper you press left+back. But the new LP2L function causes the Flipper to reboot locked when you have a PIN enabled. 
When you reboot the Flipper with a PIN from the power menu, it reboots unlocked.

Lock without a PIN always reboots unlocked, even when it displays LOCKED just before reboot.

All was tested on a factory reset Flipper including formatted SD with XFW v37

### Anything else?

Besides this really minor lock thingy, i'm love the new v37 with instant app start.

**Comment by ClaraCrazy** [comment]
right button is used for passport and cant really be changed. I can move one of the favorite app to the left button tho, that would work. However people are used to the current system with favorites being up + down. we'll see
