### ISSUE TITLE
Firmware update 

### ISSUE THREAD

**Issue by kevtheskin** [ClaraCrazy/Flipper-Xtreme#75]
Hi there Clara, Can please tell me how to fix this error during update  RPC error in command 'system.update': ERROR_INVALID_PARAMETERS
It just wont update. I tried updating with unleashed and flipper is back working again. Please help if your free.

Cheers Kev

**Comment by DereIBims** [comment]
Install original firmware and then follow the [instructions](https://github.com/ClaraCrazy/Flipper-Xtreme#-manual-update-because-qflipper-loves-to-break-every-now-and-then-for-no-reason-at-all)

**Comment by ClaraCrazy** [comment]
+1 on that.
