### ISSUE TITLE
Level system

### ISSUE THREAD

**Issue by Toosicc7up** [ClaraCrazy/Flipper-Xtreme#80]
### Describe the bug.

Just wondering if you might have changed the leveling system or something as I was getting a couple hundred points a day now the most I can get is around 80 points a day? Just wondering if this was purposeful or some type of bug.

### Reproduction

Level up

**Comment by ClaraCrazy** [comment]
yeah, we changed it as that wasnt supposed to happen. It was levelling up way too fast lol.
