### ISSUE TITLE
New animations

### ISSUE THREAD

**Issue by Toosicc7up** [ClaraCrazy/Flipper-Xtreme#81]
### Describe the bug.

Upon unlocking a new level the new animations unlocked no longer are set as the wallpaper. It usually keeps the same animation or sets one of the older animations.

### Reproduction

Level up

**Comment by ClaraCrazy** [comment]
the animations are picked random. every new level gives you an **additional** new one for the system to choose from, they cycle through every X frames (3600 in our case) and all have an equal chance of showing up (besides my personal ones, they have a slightly higher chance lol)

**Comment by Toosicc7up** [comment]
Thank you for the clarification. Before when I would unlock a new level it
would automatically put the new animation as the background. Was a nice
touch so you could see the new ones you unlocked now I have ones I've
unlocked I've never even seen three or four levels ago lol

**Comment by ClaraCrazy** [comment]
gonna look into if im able to control which animation plays. doesnt seem to be the case tho without a massive rewrite of some OFW code bc its just a pure mess lol. I hate their codebase so much xD
