### ISSUE TITLE
RFID Fuzzer Crashes 

### ISSUE THREAD

**Issue by Koyjote** [ClaraCrazy/Flipper-Xtreme#82]
Hey Clara, 
I was playing around with some RFID Reader. 
I try multiple times the RFID Fuzzer App but it won't run correctly. 
It crashes the Firmware and pass out the flipper without letting me safe anything.

**Comment by ClaraCrazy** [comment]
Bug cannot be reproduced by any staff or questioned community member, feel free to re-open with more details, if possible debug logs & a demo video.

**Comment by lanmic15** [comment]
I have the same Problem- after starting RFID-Fuzzer with "Load File" or "Load UIDs from File" the Flipper chrashed with the Info "BusFault"
