### ISSUE TITLE
Updating to V38_01112023 failing through qFlipper

### ISSUE THREAD

**Issue by cconmy** [ClaraCrazy/Flipper-Xtreme#84]
### Describe the bug.

When attempting to update to `V38_01112023` using the `MD5 (XFW-0038_01112023.tgz) = 407d4333bf36f125afbe2c0e5a23403c` file the upgrade process errors out and states `Cannot find update directory`

### Reproduction

1. Using qFlipper 1.2.2 Install from file the file XFW-0038_01112023.tgz
2. Upgrade is attempted but presents `DATA CORRUPTED` message

![Screenshot 2023-01-11 at 12 58 06](https://user-images.githubusercontent.com/12626157/211894311-3bdbe189-f41c-4095-94b4-8e616eb20e8b.png)

- Issue persists also after formatting SD card
- Issue persists after attempting to create a directory `update` on SD card as well 

# Upgrade from versions attempted:
- Official Release 0.75.0
- Flipper-Xtreme V37_01072023

### Logs

```Text
900226 [DEV] Full Update @Lubrin START
900226 [RPC] (2) Gui Start VirtualDisplay START
900226 [UTL] Region Provisioning @Lubrin START
900227 [DBG] Development hardware region detected, skipping region provisioning...
900227 [UTL] Region Provisioning @Lubrin SUCCESS
900227 [UTL] Refresh Storage Info @Lubrin START
900312 [RPC] (2) Gui Start VirtualDisplay SUCCESS
900312 [RPC] (3) Storage Info @/ext START
900367 [RPC] (3) Storage Info @/ext SUCCESS
900367 [RPC] (4) Storage Stat @/ext/Manifest START
900423 [RPC] (4) Storage Stat @/ext/Manifest SUCCESS
900467 [UTL] Refresh Storage Info @Lubrin SUCCESS
900471 [ZIP] Uncompressing file with size of 2872494 bytes...
900512 [ZIP] Uncompression finished : No Error
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/firmware.dfu.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/radio.bin.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/resources.tar.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/splash.bin.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/update.fuf.
900513 [DBG] No parent node found for Storage//Coding//Flipper_Zero//Firmware//XFW-0038_01112023/updater.bin.
900514 [DEV] Full Update @Lubrin ERROR: Cannot find update directory
900514 [BKD] Current operation finished with error: "Cannot find update directory"
```

### Anything else?

# Relevent software:
- qFlipper version: `1.2.2`
- OS: macOS Ventura 13.1

**Comment by jbohack** [comment]
Due to our massive overhaul of the firmware, qFlipper and other applications no longer take the .tgz. A manual install with a .zip will work though. A guide for manual installation is listed in our readme.md
