### ISSUE TITLE
tgz missing for release V38_01112023

### ISSUE THREAD

**Issue by xyz667** [ClaraCrazy/Flipper-Xtreme#86]
### Describe the bug.

No tgz for release V38_01112023 is provided. 
Thus no update with the mobile app possible. 

### Reproduction

go to GitHub releases tab

**Comment by ClaraCrazy** [comment]
![chrome_0qMIi9mRgJ](https://user-images.githubusercontent.com/55334727/212058882-05406a6e-3d61-452e-87cf-cdf787589e69.png)
