### ISSUE TITLE
SFW option on SD Card Unmount

### ISSUE THREAD

**Issue by IdleLime** [ClaraCrazy/Flipper-Xtreme#88]
### Describe the enhancement you're suggesting.

Not sure if possible, but it would be nice if the SFW toggle would also update the SD Card Unmounted screen to show Flipper's original graphic.

### Anything else?

I love your Flipper build so much, thank you for all the hardwork!

**Comment by jbohack** [comment]
completely possible! issue will be fixed in the next release :D
