### ISSUE TITLE
update for firmware

### ISSUE THREAD

**Issue by legioni87** [ClaraCrazy/Flipper-Xtreme#94]
### Description of the feature you're suggesting.

Clara why am I having issues finding the update file once ive transfered the extracted firmware folder to the flipper. I search in browser then update and then this firmware but I can't seem to find the corresponding update file once there. any suggestions?
It is most likely user error on my part but any suggestions would be appreciated. Thanks

**Comment by ClaraCrazy** [comment]
probably bc you downloaded the source instead of the release

**Comment by legioni87** [comment]
Thanks so much! :)
